# Generated by Django 4.1.3 on 2022-12-01 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipes.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredients', models.JSONField(default=list, validators=[recipes.validators.JSONSchemaValidator(limit_value={'description': 'The ingredients list', 'items': {'maxProperties': 3, 'properties': {'name': {'description': 'The name of the ingredient', 'maxLen': 30, 'minLen': 1, 'pattern': '^[a-zA-Z]+$', 'type': 'string'}, 'quantity': {'description': 'The quantity of the ingredient', 'maximum': 1000, 'minimum': 0, 'type': 'number'}, 'unit': {'description': 'The unit of the ingredient', 'enum': ['g', 'l', 'kg', 'n/a'], 'type': 'string'}}, 'required': ['name', 'quantity', 'unit'], 'type': 'object'}, 'minItems': 1, 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'array'}), recipes.validators.check_not_none_and_unique_ingredients])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
