# Generated by Django 4.1.3 on 2022-11-25 16:59

from django.db import migrations
import jsonfield.fields
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=jsonfield.fields.JSONField(validators=[recipes.validators.unique_ingredients]),
        ),
    ]
